# syntax=docker/dockerfile:1
# Build stage '${CREATE_STEPS}' ---------------------------------------------------------------------------------------
ARG BASE_IMG
FROM ${BASE_IMG}
ENTRYPOINT ["/bin/bash"]
WORKDIR /root

COPY --chown=root:root .vimrc /tmp/
COPY --chown=root:root .bash_aliases /tmp/
COPY --chown=root:root prepare-linux-dev-env.sh /tmp/

RUN chmod +x /tmp/prepare-linux-dev-env.sh && \
    apt-get update && \
    apt-get install --yes dos2unix && \
    dos2unix -iso -1252 /tmp/prepare-linux-dev-env.sh

ARG TARGET_USER
ARG TARGET_ENV
ARG CREATE_STEPS
ARG WHAT_IF
ARG PROJECTS
RUN /tmp/prepare-linux-dev-env.sh -u ${TARGET_USER} -e ${TARGET_ENV} -s ${CREATE_STEPS} -p ${PROJECTS} ${WHAT_IF} 2>> /tmp/err.txt 1>> /tmp/inf.txt
USER ${TARGET_USER}
WORKDIR /home/${TARGET_USER}
